name: api
type: nodejs:10

dependencies:
  nodejs:
    pm2: "^2.0.0"
    yarn: "*"

web:
  commands:
    start: "PM2_HOME=$PLATFORM_APP_DIR/run pm2 start server.js --no-daemon"
  locations:
    "/public":
      passthru: false
      root: "public"
      allow: true
      rules:
        '\.png$':
          allow: true
          expires: -1

mounts:
  "/run": "shared:files/run"

disk: 1500

hooks:
  build: |
    set -e
    yarn install
    curl -sS https://platform.sh/cli/installer | php

crons:
  snapshot:
    # Take a snapshot automatically every night at 3 am (UTC).
    spec: '0 3 * * *'
    cmd: |
      if [ "$PLATFORM_BRANCH" = master ]; then
        /app/.platformsh/bin/platform snapshot:create --yes --no-wait
      fi
  renewcert:
    # Force a redeploy at 9 am (UTC) on the 14th of every month.
    spec: '0 9 14 * *'
    cmd: |
      if [ "$PLATFORM_BRANCH" = master ]; then
        /app/.platformsh/bin/platform redeploy --yes --no-wait
      fi
